# Generated by Django 6.0 on 2025-12-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('STEM', 'Science & Tech'), ('BIZ', 'Business & Econ'), ('HUM', 'Humanities'), ('ART', 'Arts & Design'), ('GEN', 'General / Other')], default='GEN', max_length=100),
        ),
    ]
