# Generated by Django 6.0 on 2025-12-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('STEM', 'Science & Tech'), ('Business & Econs', 'Business & Econ'), ('Humanities', 'Humanities'), ('Art', 'Arts & Design'), ('General', 'General / Other')], default='GEN', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='isbn',
            field=models.CharField(max_length=13),
        ),
    ]
