# Generated by Django 5.2.10 on 2026-01-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_listing_category_alter_listing_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
